name: flutter_dojo
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_markdown: ^0.3.3
  share: ^0.6.3+5
  provider: ^4.0.4
  shared_preferences: ^0.5.6+1
  path_provider: ^1.6.0
  sqflite: ^1.2.0
  build_runner: ^1.7.3
  json_serializable: ^3.2.5
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/
    - assets/json/

    - lib/widgets/animationmotion/animatedcontainer.dart
    - lib/widgets/animationmotion/animatedalign.dart
    - lib/widgets/animationmotion/animatedbuilder.dart
    - lib/widgets/animationmotion/animatedcrossfade.dart
    - lib/widgets/animationmotion/animateddefaulttextstyle.dart
    - lib/widgets/animationmotion/animatedicon.dart
    - lib/widgets/animationmotion/animatedlist.dart
    - lib/widgets/animationmotion/animatedopacity.dart
    - lib/widgets/animationmotion/animatedphysicalmodel.dart
    - lib/widgets/animationmotion/animatedpositioned.dart
    - lib/widgets/animationmotion/animatedpadding.dart
    - lib/widgets/animationmotion/animatedsize.dart
    - lib/widgets/animationmotion/animatedswitcher.dart
    - lib/widgets/animationmotion/animatedwidget.dart
    - lib/widgets/animationmotion/animatedmodalbarrier.dart
    - lib/widgets/animationmotion/decoratedboxtransition.dart
    - lib/widgets/animationmotion/fadetransition.dart
    - lib/widgets/animationmotion/fadeinimage.dart
    - lib/widgets/animationmotion/hero.dart
    - lib/widgets/animationmotion/positionedtransition.dart
    - lib/widgets/animationmotion/rotationtransition.dart
    - lib/widgets/animationmotion/animatedtheme.dart

    - lib/widgets/appstructurenavigation/appbar.dart
    - lib/widgets/appstructurenavigation/bottomappbar.dart
    - lib/widgets/appstructurenavigation/bottomnavigationbar.dart
    - lib/widgets/appstructurenavigation/drawer.dart
    - lib/widgets/appstructurenavigation/sliverappbar.dart
    - lib/widgets/appstructurenavigation/searchdelegate.dart
    - lib/widgets/appstructurenavigation/tabpageselector.dart
    - lib/widgets/appstructurenavigation/widgetsapp.dart
    - lib/widgets/appstructurenavigation/safearea.dart
    - lib/widgets/appstructurenavigation/tabbar.dart
    - lib/widgets/appstructurenavigation/defaulttabcontroller.dart

    - lib/widgets/assetsimageicon/assetbundle.dart
    - lib/widgets/assetsimageicon/icon.dart
    - lib/widgets/assetsimageicon/icondata.dart
    - lib/widgets/assetsimageicon/icontheme.dart
    - lib/widgets/assetsimageicon/image.dart
    - lib/widgets/assetsimageicon/rawimage.dart

    - lib/widgets/async/streambuilder.dart
    - lib/widgets/async/valuelistenablebuilder.dart
    - lib/widgets/async/futurebuilder.dart
    - lib/widgets/async/inheritedmodel.dart
    - lib/widgets/async/inheritedwidget.dart
    - lib/widgets/async/valuenotifier.dart

    - lib/widgets/basic/placeholder.dart
    - lib/widgets/basic/scaffold.dart

    - lib/widgets/buttons/buttonbar.dart
    - lib/widgets/buttons/dropdownbutton.dart
    - lib/widgets/buttons/floatingactionbutton.dart
    - lib/widgets/buttons/flatbutton.dart
    - lib/widgets/buttons/iconbutton.dart
    - lib/widgets/buttons/outlinebutton.dart
    - lib/widgets/buttons/popupmenubutton.dart
    - lib/widgets/buttons/raisedbutton.dart
    - lib/widgets/buttons/rawmaterialbutton.dart
    - lib/widgets/buttons/backbutton.dart
    - lib/widgets/buttons/togglebutton.dart

    - lib/widgets/cupertino/cupertinoactionsheet.dart
    - lib/widgets/cupertino/cupertinoactivityindicator.dart
    - lib/widgets/cupertino/cupertinobutton.dart
    - lib/widgets/cupertino/cupertinoalertdialog.dart
    - lib/widgets/cupertino/cupertinodialogaction.dart
    - lib/widgets/cupertino/cupertinoslider.dart
    - lib/widgets/cupertino/cupertinoswitch.dart
    - lib/widgets/cupertino/cupertinotabbar.dart
    - lib/widgets/cupertino/cupertinosegmentedcontrol.dart
    - lib/widgets/cupertino/cupertinotabscaffold.dart
    - lib/widgets/cupertino/cupertinotimerpicker.dart
    - lib/widgets/cupertino/cupertinotabview.dart
    - lib/widgets/cupertino/cupertinonavigationbar.dart
    - lib/widgets/cupertino/cupertinopagescaffold.dart
    - lib/widgets/cupertino/cupertinocontextmenu.dart
    - lib/widgets/cupertino/cupertinoslidingsegmentedcontrol.dart
    - lib/widgets/cupertino/cupertinopopupsurface.dart
    - lib/widgets/cupertino/cupertinoscrollbar.dart
    - lib/widgets/cupertino/cupertinoicons.dart
    - lib/widgets/cupertino/cupertinocolors.dart

    - lib/widgets/dialogsalertspanels/alertdialog.dart
    - lib/widgets/dialogsalertspanels/expansionpanel.dart
    - lib/widgets/dialogsalertspanels/bottomsheet.dart
    - lib/widgets/dialogsalertspanels/simpledialog.dart
    - lib/widgets/dialogsalertspanels/snackbar.dart
    - lib/widgets/dialogsalertspanels/datepicker.dart

    - lib/widgets/input/form.dart
    - lib/widgets/input/rawkeyboardlistener.dart

    - lib/widgets/inputselections/checkbox.dart
    - lib/widgets/inputselections/checkboxlisttile.dart
    - lib/widgets/inputselections/daypicker.dart
    - lib/widgets/inputselections/radio.dart
    - lib/widgets/inputselections/radiolisttile.dart
    - lib/widgets/inputselections/slider.dart
    - lib/widgets/inputselections/slidertheme.dart
    - lib/widgets/inputselections/switch.dart
    - lib/widgets/inputselections/switchlisttile.dart
    - lib/widgets/inputselections/textfield.dart
    - lib/widgets/inputselections/textformfield.dart

    - lib/widgets/multichildlayout/column.dart
    - lib/widgets/multichildlayout/expanded.dart
    - lib/widgets/multichildlayout/flow.dart
    - lib/widgets/multichildlayout/gridpaper.dart
    - lib/widgets/multichildlayout/gridtile.dart
    - lib/widgets/multichildlayout/indexedstack.dart
    - lib/widgets/multichildlayout/layoutbuilder.dart
    - lib/widgets/multichildlayout/custommultichildlayout.dart
    - lib/widgets/multichildlayout/listbody.dart
    - lib/widgets/multichildlayout/positioned.dart
    - lib/widgets/multichildlayout/reorderablelistview.dart
    - lib/widgets/multichildlayout/row.dart
    - lib/widgets/multichildlayout/stack.dart
    - lib/widgets/multichildlayout/table.dart
    - lib/widgets/multichildlayout/wrap.dart

    - lib/widgets/paintingeffect/backdropfilter.dart
    - lib/widgets/paintingeffect/banner.dart
    - lib/widgets/paintingeffect/clip.dart
    - lib/widgets/paintingeffect/custompaint.dart
    - lib/widgets/paintingeffect/decoratedbox.dart
    - lib/widgets/paintingeffect/flutterlogo.dart
    - lib/widgets/paintingeffect/fractionaltranslation.dart
    - lib/widgets/paintingeffect/inkwell.dart
    - lib/widgets/paintingeffect/opacity.dart
    - lib/widgets/paintingeffect/colorfiltered.dart
    - lib/widgets/paintingeffect/physicalmodel.dart
    - lib/widgets/paintingeffect/rotatedbox.dart
    - lib/widgets/paintingeffect/shadermask.dart

    - lib/widgets/routing/navigator.dart

    - lib/widgets/scrolling/customscrollview.dart
    - lib/widgets/scrolling/nestedscrollview.dart
    - lib/widgets/scrolling/draggablescrollablesheet.dart
    - lib/widgets/scrolling/gridview.dart
    - lib/widgets/scrolling/listview.dart
    - lib/widgets/scrolling/scrollcontroller.dart
    - lib/widgets/scrolling/pageview.dart
    - lib/widgets/scrolling/refreshindicator.dart
    - lib/widgets/scrolling/notificationlistener.dart
    - lib/widgets/scrolling/scrollbar.dart
    - lib/widgets/scrolling/singlechildscrollview.dart
    - lib/widgets/scrolling/scrollconfiguration.dart

    - lib/widgets/singlechildlayout/align.dart
    - lib/widgets/singlechildlayout/aspectratio.dart
    - lib/widgets/singlechildlayout/baseline.dart
    - lib/widgets/singlechildlayout/center.dart
    - lib/widgets/singlechildlayout/circleavatar.dart
    - lib/widgets/singlechildlayout/constrainedbox.dart
    - lib/widgets/singlechildlayout/container.dart
    - lib/widgets/singlechildlayout/fittedbox.dart
    - lib/widgets/singlechildlayout/overflowbox.dart
    - lib/widgets/singlechildlayout/fractionallysizedbox.dart
    - lib/widgets/singlechildlayout/intrinsicheight.dart
    - lib/widgets/singlechildlayout/intrinsicwidth.dart
    - lib/widgets/singlechildlayout/offstage.dart
    - lib/widgets/singlechildlayout/padding.dart
    - lib/widgets/singlechildlayout/sizedbox.dart
    - lib/widgets/singlechildlayout/sizedoverflowbox.dart
    - lib/widgets/singlechildlayout/transform.dart
    - lib/widgets/singlechildlayout/customsinglechildlayout.dart
    - lib/widgets/singlechildlayout/unconstrainedbox.dart

    - lib/widgets/styling/flexible.dart
    - lib/widgets/styling/spacer.dart
    - lib/widgets/styling/mediaquery.dart
    - lib/widgets/styling/theme.dart
    - lib/widgets/styling/material.dart
    - lib/widgets/styling/materialslice.dart

    - lib/widgets/text/defaulttextstyle.dart
    - lib/widgets/text/richtext.dart
    - lib/widgets/text/text.dart

    - lib/widgets/touchinteractions/absorbpointer.dart
    - lib/widgets/touchinteractions/dismissible.dart
    - lib/widgets/touchinteractions/longpressdraggable.dart
    - lib/widgets/touchinteractions/dragtarget.dart
    - lib/widgets/touchinteractions/ignorepointer.dart
    - lib/widgets/touchinteractions/scrollable.dart
    - lib/widgets/touchinteractions/draggable.dart
    - lib/widgets/touchinteractions/willpopscope.dart
    - lib/widgets/touchinteractions/gesturedetector.dart
    - lib/widgets/touchinteractions/listener.dart

    - lib/pattern/viewpager/pagechangeanim.dart
    - lib/pattern/viewpager/parallaxviewpager.dart
    - lib/pattern/viewpager/slider.dart
    - lib/pattern/viewpager/anim_slider.dart
    - lib/pattern/viewpager/transformslider.dart
    - lib/pattern/viewpager/cardflip.dart
    - lib/pattern/viewpager/guide.dart

    - lib/pattern/display/bubble.dart
    - lib/pattern/display/badge.dart
    - lib/pattern/display/toast.dart
    - lib/pattern/display/layer.dart
    - lib/pattern/display/avatarlist.dart
    - lib/pattern/display/overflow.dart
    - lib/pattern/display/layerblendmode.dart
    - lib/pattern/display/delline.dart
    - lib/pattern/display/autofold.dart
    - lib/pattern/display/popup.dart
    - lib/pattern/display/shadowmask.dart
    - lib/pattern/display/rating.dart
    - lib/pattern/display/floating.dart

    - lib/pattern/gesture/gesturescale.dart

    - lib/pattern/login/login1.dart

    - lib/pattern/profile/profile1.dart

    - lib/pattern/perspective/flipcard.dart
    - lib/pattern/perspective/show3dpage.dart
    - lib/pattern/perspective/rollcard.dart

    - lib/pattern/appbar/appbar.dart
    - lib/pattern/appbar/floatingappbar.dart
    - lib/pattern/appbar/titledbottombar.dart

    - lib/pattern/listitem/itemlayout.dart

    - lib/pattern/setting/setting1.dart
    - lib/pattern/setting/menusetting.dart

    - lib/pattern/list/searchlist.dart
    - lib/pattern/list/backdrop.dart
    - lib/pattern/list/tree.dart
    - lib/pattern/list/listdetail.dart
    - lib/pattern/list/sliverheader.dart
    - lib/pattern/list/sliverheaderwitheffect.dart
    - lib/pattern/list/zoom.dart

    - lib/pattern/custompaint/custompaint1.dart

    - lib/uikit/size.dart
    - lib/uikit/position.dart
    - lib/uikit/keyboard.dart
    - lib/uikit/feedback.dart
    - lib/uikit/roundimage.dart
    - lib/uikit/drawtext.dart
    - lib/uikit/timer.dart
    - lib/uikit/screenorientation.dart
    - lib/uikit/systemui.dart
    - lib/uikit/screenshot.dart
    - lib/uikit/drawstyle.dart
    - lib/uikit/nstar.dart
    - lib/uikit/randomcolor.dart
    - lib/uikit/matrix4.dart
    - lib/uikit/gesturepainter.dart
    - lib/uikit/clock.dart
    - lib/uikit/visibility.dart
    - lib/uikit/curves.dart
    - lib/uikit/pullrefresh.dart
    - lib/uikit/color.dart
    - lib/uikit/linemetrics.dart
    - lib/uikit/interpolator.dart
    - lib/uikit/curvefitting.dart
    - lib/uikit/drawimage.dart
    - lib/uikit/repaintboundary.dart

    - lib/backend/provider.dart
    - lib/backend/stream.dart
    - lib/backend/sharedpreferences.dart
    - lib/backend/sqflite.dart
    - lib/backend/pageroute.dart
    - lib/backend/json.dart
    - lib/backend/lifecycle.dart
    - lib/backend/catcherror.dart
    - lib/backend/key.dart
    - lib/backend/statemanagement.dart
    - lib/backend/providerstate.dart
    - lib/backend/singleton.dart

    - lib/animation/tween/tweenanimationbuilder.dart
    - lib/animation/tween/testanim1.dart
    - lib/animation/tween/testanim2.dart
    - lib/animation/tween/testanim3.dart
    - lib/animation/tween/slidecard.dart
    - lib/animation/tween/rotatemenu.dart
    - lib/animation/tween/gift.dart

    - lib/animation/barchat/bar.dart

    - lib/animation/animlist/deleteanimlist.dart
    - lib/animation/animlist/animlist.dart

    - lib/animation/animbutton/foldablebutton.dart
    - lib/animation/animbutton/progressbutton.dart

    - lib/animation/animation/curve.dart
    - lib/animation/animation/typewriter.dart
    - lib/animation/animation/sequence.dart
    - lib/animation/animation/focus.dart
    - lib/animation/animation/bouncing.dart
    - lib/animation/animation/staggeranimation.dart
    - lib/animation/animation/wave.dart
    - lib/animation/animation/showup.dart
    - lib/animation/animation/curveline.dart
    - lib/animation/animation/implicitlyanimatedwidget.dart

    - lib/animation/loading/loading.dart
    - lib/animation/loading/customprogress.dart

    - lib/animation/scrollanimation/scrollinganimation1.dart
    - lib/animation/scrollanimation/scrollinganimation2.dart
    - lib/animation/scrollanimation/scrollinganimation3.dart
    - lib/animation/scrollanimation/listtopbottom.dart
    - lib/animation/scrollanimation/scrollparallax.dart

  fonts:
    - family: RubikMonoOne
      fonts:
        - asset: fonts/RubikMonoOne.ttf
          weight: 600
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # assets:
  #  - images/a_dot_burr.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
